[2025-06-26T15:10:19.169+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-26T15:03:36.633712+00:00 [queued]>
[2025-06-26T15:10:19.186+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-26T15:03:36.633712+00:00 [queued]>
[2025-06-26T15:10:19.187+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-26T15:10:19.230+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-06-26 15:03:36.633712+00:00
[2025-06-26T15:10:19.241+0000] {standard_task_runner.py:60} INFO - Started process 188 to run task
[2025-06-26T15:10:19.259+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-06-26T15:03:36.633712+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpndg31hi4']
[2025-06-26T15:10:19.264+0000] {standard_task_runner.py:88} INFO - Job 267: Subtask carregamento_postgres
[2025-06-26T15:10:19.405+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-06-26T15:03:36.633712+00:00 [running]> on host 6afc1f3750fb
[2025-06-26T15:10:19.648+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T15:03:36.633712+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-26T15:03:36.633712+00:00'
[2025-06-26T15:10:19.755+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-06-26T15:10:20.149+0000] {docker.py:429} INFO - Running meltano install...
[2025-06-26T15:10:22.441+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:22.440766Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-06-26T15:10:22.467+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:22.466478Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-06-26T15:10:22.493+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:22.492983Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-06-26T15:10:22.533+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:22.532538Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-06-26T15:10:22.579+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:22.577519Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-06-26T15:10:22.666+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:22.664486Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-06-26T15:10:22.745+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:22.743837Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-06-26T15:10:22.867+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:22.863978Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-06-26T15:10:26.014+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:26.013088Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-06-26T15:10:26.071+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:26.069982Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-06-26T15:10:31.971+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:31.970356Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-06-26T15:10:32.430+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:32.429098Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-06-26T15:10:34.351+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:34.350370Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-06-26T15:10:34.858+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:34.857976Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-06-26T15:10:35.174+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:35.173504Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2m2025-06-26T15:10:35.173845Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-06-26T15:10:36.171+0000] {docker.py:429} INFO - Meltano install completed. Executing command: meltano el tap-csv-latest target-postgres
[2025-06-26T15:10:37.288+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:37.287810Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-06-26T15:10:37.729+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:37.729161Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m
[2025-06-26T15:10:38.739+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.738682Z[0m [[32m[1minfo     [0m] [1mNo CSV file definitions found.[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.913+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.912761Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.2[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-06-26T15:10:38.913071Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.914+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.913370Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.915+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.913607Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.915+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.913901Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.917+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.914116Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1442, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.919+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.914986Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.921+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.915434Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1363, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.921+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.916173Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.922+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.917026Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/plugin_base.py", line 97, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.923+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.917784Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.923+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.918288Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1226, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.923+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.918764Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.924+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.919224Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 794, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.924+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.919717Z[0m [[32m[1minfo     [0m] [1m    return callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.924+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.920188Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 583, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.925+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.920804Z[0m [[32m[1minfo     [0m] [1m    target = cls(             [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.925+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.921357Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/target.py", line 67, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.925+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.921841Z[0m [[32m[1minfo     [0m] [1m    and self.config.get("dialect+driver") is not None[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:38.926+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:38.922252Z[0m [[32m[1minfo     [0m] [1mAssertionError: Need either the sqlalchemy_url to be set or host, port, user, password, and dialect+driver to be set[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:39.032+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:39.031621Z[0m [[31m[1merror    [0m] [1mExtraction failed             [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m'No CSV file definitions found.'[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m
[2m2025-06-26T15:10:39.031868Z[0m [[31m[1merror    [0m] [1mLoading failed                [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m'AssertionError: Need either the sqlalchemy_url to be set or host, port, user, password, and dialect+driver to be set'[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m
[2025-06-26T15:10:39.032+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:39.032190Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Extractor and loader failed.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:39.033+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:39.032404Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:39.033+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:39.032669Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-06-26T151037--tap-csv-latest--target-postgres/8e0bd61f-f269-454b-a0b2-340a43a7a5e2/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:39.033+0000] {docker.py:429} INFO - [2m2025-06-26T15:10:39.032910Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m8e0bd61f-f269-454b-a0b2-340a43a7a5e2[0m [36mstate_id[0m=[35m2025-06-26T151037--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-26T15:10:39.047+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

ELT could not be completed: Extractor and loader failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-06-26T151037--tap-csv-latest--target-postgres/8e0bd61f-f269-454b-a0b2-340a43a7a5e2/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2025-06-26T15:10:40.379+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-06-26T15:10:40.386+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250626T150336, start_date=20250626T151019, end_date=20250626T151040
[2025-06-26T15:10:40.407+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 267 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 188)
[2025-06-26T15:10:40.446+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-26T15:10:40.461+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
