[2025-06-25T20:26:42.039+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-25T20:25:36.532955+00:00 [queued]>
[2025-06-25T20:26:42.048+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-25T20:25:36.532955+00:00 [queued]>
[2025-06-25T20:26:42.049+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-25T20:26:42.062+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-06-25 20:25:36.532955+00:00
[2025-06-25T20:26:39.587+0000] {standard_task_runner.py:60} INFO - Started process 231 to run task
[2025-06-25T20:26:39.590+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-06-25T20:25:36.532955+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu73aairv']
[2025-06-25T20:26:39.595+0000] {standard_task_runner.py:88} INFO - Job 171: Subtask carregamento_postgres
[2025-06-25T20:26:39.654+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-06-25T20:25:36.532955+00:00 [running]> on host 6afc1f3750fb
[2025-06-25T20:26:39.760+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T20:25:36.532955+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T20:25:36.532955+00:00'
[2025-06-25T20:26:39.840+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-06-25T20:26:40.198+0000] {docker.py:429} INFO - Running meltano install...
[2025-06-25T20:26:41.554+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:41.554085Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-06-25T20:26:41.570+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:41.569741Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-06-25T20:26:41.586+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:41.585396Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-06-25T20:26:41.603+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:41.602558Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-06-25T20:26:41.626+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:41.625836Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-06-25T20:26:41.659+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:41.658858Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-06-25T20:26:41.699+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:41.698170Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-06-25T20:26:41.737+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:41.736206Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-06-25T20:26:43.448+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:43.448080Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-06-25T20:26:43.484+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:43.483445Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-06-25T20:26:48.968+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:48.967914Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-06-25T20:26:49.102+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:49.101468Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-06-25T20:26:50.866+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:50.865322Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-06-25T20:26:50.988+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:50.988169Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-06-25T20:26:51.051+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:51.051172Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2m2025-06-25T20:26:51.051415Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-06-25T20:26:52.078+0000] {docker.py:429} INFO - Meltano install completed. Executing command: meltano el tap-csv-latest target-postgres
[2025-06-25T20:26:53.285+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:53.284927Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-06-25T20:26:53.686+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:53.685917Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m
[2025-06-25T20:26:54.809+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:54.808232Z[0m [[32m[1minfo     [0m] [1mNo CSV file definitions found.[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.024+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.023697Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.2[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-06-25T20:26:55.024037Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.025+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.024238Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.025+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.024410Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.025+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.024653Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.026+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.024896Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1442, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.026+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.025522Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.028+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.025874Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1363, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.036+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.026390Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-06-25T20:26:55.026726Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/plugin_base.py", line 97, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.036+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.027066Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.036+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.027780Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1226, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.037+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.030013Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.037+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.031275Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 794, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.037+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.031757Z[0m [[32m[1minfo     [0m] [1m    return callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-06-25T20:26:55.032238Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 583, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.037+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.032922Z[0m [[32m[1minfo     [0m] [1m    target = cls(             [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.038+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.033626Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/target.py", line 67, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.038+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.034128Z[0m [[32m[1minfo     [0m] [1m    and self.config.get("dialect+driver") is not None[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.038+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.034512Z[0m [[32m[1minfo     [0m] [1mAssertionError: Need either the sqlalchemy_url to be set or host, port, user, password, and dialect+driver to be set[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.133+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.133128Z[0m [[31m[1merror    [0m] [1mExtraction failed             [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m'No CSV file definitions found.'[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m
[2m2025-06-25T20:26:55.133381Z[0m [[31m[1merror    [0m] [1mLoading failed                [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m'AssertionError: Need either the sqlalchemy_url to be set or host, port, user, password, and dialect+driver to be set'[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m
[2025-06-25T20:26:55.134+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.133783Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Extractor and loader failed.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.134+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.134141Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.135+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.134378Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-06-25T202653--tap-csv-latest--target-postgres/f5a98679-9f41-4cd1-9bd4-bdd1575b8a87/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.135+0000] {docker.py:429} INFO - [2m2025-06-25T20:26:55.134629Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35mf5a98679-9f41-4cd1-9bd4-bdd1575b8a87[0m [36mstate_id[0m=[35m2025-06-25T202653--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:26:55.150+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

ELT could not be completed: Extractor and loader failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-06-25T202653--tap-csv-latest--target-postgres/f5a98679-9f41-4cd1-9bd4-bdd1575b8a87/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2025-06-25T20:26:56.329+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-06-25T20:26:56.337+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250625T202536, start_date=20250625T202642, end_date=20250625T202656
[2025-06-25T20:26:56.361+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 171 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 231)
[2025-06-25T20:26:56.390+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-25T20:26:56.405+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
