[2025-07-09T21:55:39.213+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T21:54:52.345768+00:00 [queued]>
[2025-07-09T21:55:39.221+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T21:54:52.345768+00:00 [queued]>
[2025-07-09T21:55:39.221+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-09T21:55:39.232+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-09 21:54:52.345768+00:00
[2025-07-09T21:55:39.236+0000] {standard_task_runner.py:60} INFO - Started process 192 to run task
[2025-07-09T21:55:39.239+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-09T21:54:52.345768+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/northwind.py', '--cfg-path', '/tmp/tmpasz0xoaz']
[2025-07-09T21:55:39.241+0000] {standard_task_runner.py:88} INFO - Job 124: Subtask carregamento_postgres
[2025-07-09T21:55:39.286+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-09T21:54:52.345768+00:00 [running]> on host 006946d6dbce
[2025-07-09T21:55:39.364+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T21:54:52.345768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T21:54:52.345768+00:00'
[2025-07-09T21:55:39.411+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-09T21:55:37.097+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-09T21:55:38.462+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:38.461418Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-09T21:55:38.475+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:38.474296Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-09T21:55:38.502+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:38.501913Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-09T21:55:38.538+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:38.537491Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-09T21:55:38.565+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:38.564305Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-09T21:55:38.611+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:38.610543Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-09T21:55:38.665+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:38.661857Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-09T21:55:38.728+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:38.724501Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-09T21:55:40.005+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:40.004265Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-09T21:55:40.042+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:40.042077Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-09T21:55:43.971+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:43.970004Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-09T21:55:44.038+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:44.037984Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-07-09T21:55:45.479+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:45.478279Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-09T21:55:45.522+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:45.522262Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-09T21:55:46.032+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:46.031680Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-07-09T21:55:46.032+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:46.032064Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-09T21:55:46.920+0000] {docker.py:429} INFO - Meltano install completed. Executing command: bash -c meltano config tap-csv-latest set csv_files_definition /opt/meltano/config/tap-csv-latest.json && meltano el tap-csv-latest target-postgres
[2025-07-09T21:55:48.643+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:48.643036Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2025-07-09T21:55:49.098+0000] {docker.py:429} INFO - Extractor 'tap-csv-latest' setting 'csv_files_definition' was set in `meltano.yml`: '/opt/meltano/config/tap-csv-latest.json'
[2025-07-09T21:55:50.994+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:50.993917Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-09T21:55:51.350+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:51.349274Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m
[2025-07-09T21:55:52.303+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.302863Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'order_details'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.304+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.303410Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.468+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.467781Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.470+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.469251Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.470+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.469610Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.471+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.469922Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.472+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.470360Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.622+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.621590Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.622+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.621971Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.623+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.622456Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.623+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.622861Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.628+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.626904Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.629+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.627674Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.630+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.628617Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.630+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.629451Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.630+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.630008Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.631+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.630394Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.631+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.630911Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.631+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.631225Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.632+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.631730Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.632+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.632127Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.633+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.632657Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.634+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.633150Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.634+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.633658Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.635+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.634112Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.635+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.635153Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.636+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.635769Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.637+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.636277Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.637+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.636828Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.638+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.637638Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.639+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.638065Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.640+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.639216Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.640+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.639930Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.641+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.640657Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.642+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.640980Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.641277Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.641504Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.642+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.641790Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.642+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.642161Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 96, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.643+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.642561Z[0m [[32m[1minfo     [0m] [1m    attempts = conninfo_attempts(params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.642885Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/_conninfo_attempts.py", line 53, in conninfo_attempts[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.644+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.643225Z[0m [[32m[1minfo     [0m] [1m    raise e.OperationalError(str(last_exc))[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.644+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.644044Z[0m [[32m[1minfo     [0m] [1mpsycopg.OperationalError: [Errno -2] Name or service not known[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.645+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.644495Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.645+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.644886Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.645+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.645218Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.646+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.645776Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.646+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.646166Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.646500Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.647+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.646805Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.648+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.647452Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.648+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.647904Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1082, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.648+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.648211Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.649+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.648513Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 98, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.649+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.648817Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.650+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.649099Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.650+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.649418Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.651+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.649779Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.651+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.650157Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.652+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.650560Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 588, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.652+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.650864Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.653+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.651278Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 775, in listen[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.653+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.651651Z[0m [[32m[1minfo     [0m] [1m    counter = self.process_lines(file_input)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.654+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.651971Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 801, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.654+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.652385Z[0m [[32m[1minfo     [0m] [1m    return self.message_reader.process_lines([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.654+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.652744Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/singerlib/encoding/base.py", line 70, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.655+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.653079Z[0m [[32m[1minfo     [0m] [1m    callback(line_dict)       [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.655+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.653416Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 403, in _process_schema_message[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.655+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.653786Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.656+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.654099Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 817, in get_sink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.656+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.654430Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.656+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.654978Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 751, in add_sqlsink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.657+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.655831Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.657+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.656377Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/target_postgres/sinks.py", line 58, in setup[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.658+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.656973Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema(self.schema_name)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.658+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.657705Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1367, in prepare_schema[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.659+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.658576Z[0m [[32m[1minfo     [0m] [1m    if not self.schema_exists(schema_name):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.659+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.659108Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1200, in schema_exists[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.660+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.659786Z[0m [[32m[1minfo     [0m] [1m    schemas = set(sa.inspect(self._engine).get_schema_names())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.661+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.660640Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 140, in inspect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.662+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.661410Z[0m [[32m[1minfo     [0m] [1m    ret = reg(subject)        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.662+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.661984Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 313, in _engine_insp[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.663+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.662391Z[0m [[32m[1minfo     [0m] [1m    return Inspector._construct(Inspector._init_engine, bind)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.663+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.662889Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 246, in _construct[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.664+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.663252Z[0m [[32m[1minfo     [0m] [1m    init(self, bind)          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.664+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.663774Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 257, in _init_engine[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.664+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.664193Z[0m [[32m[1minfo     [0m] [1m    engine.connect().close()  [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.665+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.664735Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3273, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.665+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.665149Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.666+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.665631Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 147, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.666+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.666009Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.667+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.666450Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.667+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.666807Z[0m [[32m[1minfo     [0m] [1m    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.667+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.667191Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.668+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.667642Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.669+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.668062Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.670+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.668428Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.668936Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.669350Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.671+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.669854Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.670287Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.670735Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.672+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.671254Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T21:55:52.671772Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.673+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.672215Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.673+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.672623Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.673+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.673012Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.674+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.673387Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.674+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.673868Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.674+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.674429Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.675+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.675135Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.676+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.675586Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.676+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.676064Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.676+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.676435Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.677+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.676886Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.678+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.677388Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.678+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.677892Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.678+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.678322Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.679+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.678944Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.680+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.679527Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.680+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.679967Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.681+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.680378Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.681+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.680936Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.682+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.681552Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 96, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.682+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.682223Z[0m [[32m[1minfo     [0m] [1m    attempts = conninfo_attempts(params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.683+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.682749Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/_conninfo_attempts.py", line 53, in conninfo_attempts[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.684+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.683387Z[0m [[32m[1minfo     [0m] [1m    raise e.OperationalError(str(last_exc))[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.684+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.683817Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.OperationalError: (psycopg.OperationalError) [Errno -2] Name or service not known[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:52.684+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.684184Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/20/e3q8)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1236ad98-6620-42f8-b16c-0019819f7e10[0m [36mstate_id[0m=[35m2025-07-09T215551--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T21:55:53.142+0000] {docker.py:429} INFO - [2m2025-07-09T21:55:52.818165Z[0m [[31m[1merror    [0m] [1m                              [0m
[31m╭─[0m[31m────────────────────[0m[31m [0m[1;31mTraceback [0m[1;2;31m(most recent call last)[0m[31m [0m[31m─────────────────────[0m[31m─╮[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1moutput_logger.py[0m:217  [31m│[0m
[31m│[0m in redirect_logging                                                          [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m214 [0m[2m│   │   │   [0m*ignore_errors,                                            [31m│[0m
[31m│[0m   [2m215 [0m[2m│   │   [0m)                                                              [31m│[0m
[31m│[0m   [2m216 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m [31m❱ [0m217 [2m│   │   │   [0m[94myield[0m                                                      [31m│[0m
[31m│[0m   [2m218 [0m[2m│   │   [0m[94mexcept[0m ignored_errors:                                         [31m│[0m
[31m│[0m   [2m219 [0m[2m│   │   │   [0m[94mraise[0m                                                      [31m│[0m
[31m│[0m   [2m220 [0m[2m│   │   [0m[94mexcept[0m RunnerError [94mas[0m err:                                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:475 in _redirect_output [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m472 [0m[2m│   [0m[94mwith[0m meltano_stdout.redirect_logging(ignore_errors=(CliError,)):   [31m│[0m
[31m│[0m   [2m473 [0m[2m│   │   [0m[94masync[0m [94mwith[0m meltano_stdout.redirect_stdout(), meltano_stderr.re [31m│[0m
[31m│[0m   [2m474 [0m[2m│   │   │   [0m[94mtry[0m:                                                       [31m│[0m
[31m│[0m [31m❱ [0m475 [2m│   │   │   │   [0m[94myield[0m                                                  [31m│[0m
[31m│[0m   [2m476 [0m[2m│   │   │   [0m[94mexcept[0m CliError [94mas[0m err:                                    [31m│[0m
[31m│[0m   [2m477 [0m[2m│   │   │   │   [0merr.print()                                            [31m│[0m
[31m│[0m   [2m478 [0m[2m│   │   │   │   [0m[94mraise[0m                                                  [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:508 in _run_elt         [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m505 [0m[2m│   │   │   [0m[94mif[0m elt_context.only_transform:                             [31m│[0m
[31m│[0m   [2m506 [0m[2m│   │   │   │   [0mlog.info([33m"[0m[33mExtract & load skipped.[0m[33m"[0m)                    [31m│[0m
[31m│[0m   [2m507 [0m[2m│   │   │   [0m[94melse[0m:                                                      [31m│[0m
[31m│[0m [31m❱ [0m508 [2m│   │   │   │   [0m[94mawait[0m _run_extract_load(log, elt_context, output_logge [31m│[0m
[31m│[0m   [2m509 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m510 [0m[2m│   │   │   [0m[94mif[0m elt_context.transformer:                                [31m│[0m
[31m│[0m   [2m511 [0m[2m│   │   │   │   [0mlog.warning(                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:581 in                  [31m│[0m
[31m│[0m _run_extract_load                                                            [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m578 [0m[2m│   │   │   [0m[94mwith[0m loader_log.line_writer() [94mas[0m loader_log_writer:        [31m│[0m
[31m│[0m   [2m579 [0m[2m│   │   │   │   [0m[94mwith[0m extractor_out_writer_ctxmgr() [94mas[0m extractor_out_wr [31m│[0m
[31m│[0m   [2m580 [0m[2m│   │   │   │   │   [0m[94mwith[0m loader_out_writer_ctxmgr() [94mas[0m loader_out_writ [31m│[0m
[31m│[0m [31m❱ [0m581 [2m│   │   │   │   │   │   [0m[94mawait[0m singer_runner.run(                       [31m│[0m
[31m│[0m   [2m582 [0m[2m│   │   │   │   │   │   │   [0m**kwargs,                                  [31m│[0m
[31m│[0m   [2m583 [0m[2m│   │   │   │   │   │   │   [0mextractor_log=extractor_log_writer,        [31m│[0m
[31m│[0m   [2m584 [0m[2m│   │   │   │   │   │   │   [0mloader_log=loader_log_writer,              [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:229 in run   [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m226 [0m[2m│   │   │   [0mtap.prepared([96mself[0m.context.session),                        [31m│[0m
[31m│[0m   [2m227 [0m[2m│   │   │   [0mtarget.prepared([96mself[0m.context.session),                     [31m│[0m
[31m│[0m   [2m228 [0m[2m│   │   [0m):                                                             [31m│[0m
[31m│[0m [31m❱ [0m229 [2m│   │   │   [0m[94mawait[0m [96mself[0m.invoke(  [2m# noqa: RET503[0m                         [31m│[0m
[31m│[0m   [2m230 [0m[2m│   │   │   │   [0mtap,                                                   [31m│[0m
[31m│[0m   [2m231 [0m[2m│   │   │   │   [0mtarget,                                                [31m│[0m
[31m│[0m   [2m232 [0m[2m│   │   │   │   [0mextractor_log=extractor_log,                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:148 in       [31m│[0m
[31m│[0m invoke                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m145 [0m[2m│   │   │   │   │   [0m)                                                  [31m│[0m
[31m│[0m   [2m146 [0m[2m│   │   │   │   [0m                                                       [31m│[0m
[31m│[0m   [2m147 [0m[2m│   │   │   │   [0mfailed_future = output_futures_failed.pop()            [31m│[0m
[31m│[0m [31m❱ [0m148 [2m│   │   │   │   [0m[94mraise[0m failed_future.exception()                        [31m│[0m
[31m│[0m   [2m149 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m150 [0m[2m│   │   │   [0m[2m# If all of the output handlers completed without raising [0m [31m│[0m
[31m│[0m   [2m151 [0m[2m│   │   │   [0m[2m# exception, we still need to wait for the tap or target t[0m [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:305 in       [31m│[0m
[31m│[0m capture_subprocess_output                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m302 [0m[2m│   │   │   [0m[94mcontinue[0m                                                   [31m│[0m
[31m│[0m   [2m303 [0m[2m│   │   [0m                                                               [31m│[0m
[31m│[0m   [2m304 [0m[2m│   │   [0m[94mfor[0m writer [95min[0m line_writers:                                    [31m│[0m
[31m│[0m [31m❱ [0m305 [2m│   │   │   [0m[94mif[0m [95mnot[0m [94mawait[0m _write_line_writer(writer, line):             [31m│[0m
[31m│[0m   [2m306 [0m[2m│   │   │   │   [0m[2m# If the destination stream is closed, we can stop cap[0m [31m│[0m
[31m│[0m   [2m307 [0m[2m│   │   │   │   [0m[94mreturn[0m                                                 [31m│[0m
[31m│[0m   [2m308 [0m                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:273 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m   [2m271 [0m[2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m [31m❱ [0m273 [2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m   [2m275 [0m[2m│   [0m[94melse[0m:                                                              [31m│[0m
[31m│[0m   [2m276 [0m[2m│   │   [0mwriter.writeline(line.decode(errors=[33m"[0m[33mreplace[0m[33m"[0m))                [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:359 in wait_closed               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m356 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.is_closing()                            [31m│[0m
[31m│[0m   [2m357 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m358 [0m[2m│   [0m[94masync[0m [94mdef[0m[90m [0m[92mwait_closed[0m([96mself[0m):                                       [31m│[0m
[31m│[0m [31m❱ [0m359 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._get_close_waiter([96mself[0m)                   [31m│[0m
[31m│[0m   [2m360 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m361 [0m[2m│   [0m[94mdef[0m[90m [0m[92mget_extra_info[0m([96mself[0m, name, default=[94mNone[0m):                      [31m│[0m
[31m│[0m   [2m362 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.get_extra_info(name, default)           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:271 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m268 [0m[2m│   [0m[94mif[0m [96misinstance[0m(writer, asyncio.StreamWriter):                       [31m│[0m
[31m│[0m   [2m269 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m [31m❱ [0m271 [2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m   [2m273 [0m[2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:387 in drain                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m384 [0m[2m│   │   │   [0m[2m# in a loop would never call connection_lost(), so it[0m      [31m│[0m
[31m│[0m   [2m385 [0m[2m│   │   │   [0m[2m# would not see an error when the socket is closed.[0m        [31m│[0m
[31m│[0m   [2m386 [0m[2m│   │   │   [0m[94mawait[0m sleep([94m0[0m)                                             [31m│[0m
[31m│[0m [31m❱ [0m387 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._drain_helper()                           [31m│[0m
[31m│[0m   [2m388 [0m                                                                       [31m│[0m
[31m│[0m   [2m389 [0m                                                                       [31m│[0m
[31m│[0m   [2m390 [0m[94mclass[0m[90m [0m[4;92mStreamReader[0m:                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:197 in _drain_helper             [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m194 [0m[2m│   │   [0m[94massert[0m waiter [95mis[0m [94mNone[0m [95mor[0m waiter.cancelled()                    [31m│[0m
[31m│[0m   [2m195 [0m[2m│   │   [0mwaiter = [96mself[0m._loop.create_future()                            [31m│[0m
[31m│[0m   [2m196 [0m[2m│   │   [0m[96mself[0m._drain_waiter = waiter                                    [31m│[0m
[31m│[0m [31m❱ [0m197 [2m│   │   [0m[94mawait[0m waiter                                                   [31m│[0m
[31m│[0m   [2m198 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m199 [0m[2m│   [0m[94mdef[0m[90m [0m[92m_get_close_waiter[0m([96mself[0m, stream):                               [31m│[0m
[31m│[0m   [2m200 [0m[2m│   │   [0m[94mraise[0m [96mNotImplementedError[0m                                      [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────╯[0m
[1;91mBrokenPipeError[0m
[2025-07-09T21:55:53.157+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.
[2025-07-09T21:55:54.215+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-09T21:55:54.223+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250709T215452, start_date=20250709T215539, end_date=20250709T215554
[2025-07-09T21:55:54.244+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 124 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 192)
[2025-07-09T21:55:54.263+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-09T21:55:54.285+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
