[2025-07-07T20:17:53.887+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-07T20:10:36.921622+00:00 [queued]>
[2025-07-07T20:17:54.080+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-07T20:10:36.921622+00:00 [queued]>
[2025-07-07T20:17:54.082+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-07T20:17:54.257+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-07 20:10:36.921622+00:00
[2025-07-07T20:17:54.340+0000] {standard_task_runner.py:60} INFO - Started process 253 to run task
[2025-07-07T20:17:54.393+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-07T20:10:36.921622+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/northwind.py', '--cfg-path', '/tmp/tmpw5rrssuf']
[2025-07-07T20:17:54.462+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask carregamento_postgres
[2025-07-07T20:17:55.489+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-07T20:10:36.921622+00:00 [running]> on host f4a43ea430c1
[2025-07-07T20:17:57.009+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T20:10:36.921622+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T20:10:36.921622+00:00'
[2025-07-07T20:17:57.848+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-07T20:18:17.812+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-07T20:18:49.551+0000] {docker.py:429} INFO - [2m2025-07-07T20:18:49.545406Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-07T20:18:49.749+0000] {docker.py:429} INFO - [2m2025-07-07T20:18:49.744924Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-07T20:18:50.000+0000] {docker.py:429} INFO - [2m2025-07-07T20:18:49.995638Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-07T20:18:50.254+0000] {docker.py:429} INFO - [2m2025-07-07T20:18:50.248537Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-07T20:18:50.532+0000] {docker.py:429} INFO - [2m2025-07-07T20:18:50.522961Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-07T20:18:50.883+0000] {docker.py:429} INFO - [2m2025-07-07T20:18:50.873105Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-07T20:18:51.297+0000] {docker.py:429} INFO - [2m2025-07-07T20:18:51.281402Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-07T20:18:52.682+0000] {docker.py:429} INFO - [2m2025-07-07T20:18:52.674908Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-07T20:19:21.519+0000] {docker.py:429} INFO - [2m2025-07-07T20:19:21.506228Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-07T20:19:21.530+0000] {docker.py:429} INFO - [2m2025-07-07T20:19:21.526372Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-07T20:19:51.001+0000] {docker.py:429} INFO - [2m2025-07-07T20:19:50.990646Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-07T20:19:51.578+0000] {docker.py:429} INFO - [2m2025-07-07T20:19:51.564784Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-07-07T20:20:07.930+0000] {docker.py:429} INFO - [2m2025-07-07T20:20:07.924447Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-07T20:20:09.364+0000] {docker.py:429} INFO - [2m2025-07-07T20:20:09.360357Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-07T20:20:12.920+0000] {docker.py:429} INFO - [2m2025-07-07T20:20:12.617412Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-07-07T20:20:13.795+0000] {docker.py:429} INFO - [2m2025-07-07T20:20:12.729236Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-07T20:20:22.662+0000] {docker.py:429} INFO - Meltano install completed. Executing command: bash -c meltano config tap-csv-latest set csv_files_definition /opt/meltano/config/tap-csv-latest.json && meltano el tap-csv-latest target-postgres
[2025-07-07T20:20:59.034+0000] {docker.py:429} INFO - [2m2025-07-07T20:20:59.026626Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2025-07-07T20:21:01.105+0000] {docker.py:429} INFO - Extractor 'tap-csv-latest' setting 'csv_files_definition' was set in `meltano.yml`: '/opt/meltano/config/tap-csv-latest.json'
[2025-07-07T20:21:31.494+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:31.487863Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-07T20:21:35.597+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:35.592551Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m
[2025-07-07T20:21:45.243+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.234523Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.249+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.240989Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/bin/tap-csv", line 8, in <module>[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.254+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.247493Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TapCSV.cli())    [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.261+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.252186Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.263+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.257104Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.267+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.260575Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/click/core.py", line 1082, in main[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.274+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.264026Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.276+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.269333Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 93, in invoke[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.281+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.275389Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.285+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.278746Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.287+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.280717Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.289+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.283021Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.293+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.288062Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.297+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.292212Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 516, in invoke[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.300+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.296029Z[0m [[32m[1minfo     [0m] [1m    tap = cls(                [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.303+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.299132Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 118, in __init__[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.306+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.301384Z[0m [[32m[1minfo     [0m] [1m    self.setup_mapper()       [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.310+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.305046Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 194, in setup_mapper[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.313+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.309241Z[0m [[32m[1minfo     [0m] [1m    self.mapper.register_raw_streams_from_catalog(self.catalog)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.317+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.312028Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 187, in catalog[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.324+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.314701Z[0m [[32m[1minfo     [0m] [1m    self._catalog = self.input_catalog or self._singer_catalog[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-07T20:21:45.317278Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 340, in _singer_catalog[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.329+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.320991Z[0m [[32m[1minfo     [0m] [1m    for stream in self.streams.values()[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.337+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.328272Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 149, in streams[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.340+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.332958Z[0m [[32m[1minfo     [0m] [1m    for stream in self.load_streams():[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.343+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.336131Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 373, in load_streams[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.346+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.339181Z[0m [[32m[1minfo     [0m] [1m    for stream in self.discover_streams():[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.358+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.342953Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/tap_csv/tap.py", line 89, in discover_streams[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.360+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.352988Z[0m [[32m[1minfo     [0m] [1m    return [                  [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.365+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.357037Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/tap_csv/tap.py", line 92, in <listcomp>[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.375+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.359834Z[0m [[32m[1minfo     [0m] [1m    name=file_config.get("entity"),[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:45.377+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:45.363534Z[0m [[32m[1minfo     [0m] [1mAttributeError: 'str' object has no attribute 'get'[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:46.705+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:46.701384Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:46.718+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:46.712807Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:46.732+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:46.716287Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:46.735+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:46.721212Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:46.738+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:46.727066Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:46.741+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:46.731806Z[0m [[32m[1minfo     [0m] [1mThe `dialect+driver` configuration option is deprecated. Please set it to `postgresql+psycopg`, as this will be the hard-coded value in the future.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:46.743+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:46.734878Z[0m [[32m[1minfo     [0m] [1mReader 'target-postgres' completed processing 0 lines of input (0 schemas, 0 records, 0 batch manifests, 0 state messages, 0 activate version messages).[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:47.287+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:47.283276Z[0m [[31m[1merror    [0m] [1mExtraction failed             [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m"AttributeError: 'str' object has no attribute 'get'"[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m
[2025-07-07T20:21:47.296+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:47.292036Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Extractor failed.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:47.299+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:47.294945Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:47.301+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:47.298261Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-07-07T202132--tap-csv-latest--target-postgres/0a82c6f2-deea-45ad-b8c4-1e11369e4527/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:47.305+0000] {docker.py:429} INFO - [2m2025-07-07T20:21:47.300728Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m0a82c6f2-deea-45ad-b8c4-1e11369e4527[0m [36mstate_id[0m=[35m2025-07-07T202132--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-07T20:21:47.380+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

ELT could not be completed: Extractor failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-07-07T202132--tap-csv-latest--target-postgres/0a82c6f2-deea-45ad-b8c4-1e11369e4527/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2025-07-07T20:21:53.175+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-07T20:21:53.330+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250707T201036, start_date=20250707T201753, end_date=20250707T202153
[2025-07-07T20:21:54.460+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-07T20:21:54.477+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-07T20:21:54.483+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-07T20:21:54.585+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-07T20:21:54.587+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-07T20:21:54.594+0000] {taskinstance.py:826} ERROR - Failed to send email to: ['lrbf@cin.ufpe.br']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2499, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2516, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1000, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 824, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2946, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1002, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-07T20:21:54.926+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 253)
[2025-07-07T20:21:55.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-07T20:21:55.488+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
