[2025-07-09T20:12:18.618+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:06:20.749604+00:00 [queued]>
[2025-07-09T20:12:18.636+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:06:20.749604+00:00 [queued]>
[2025-07-09T20:12:18.637+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-09T20:12:18.656+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-09 20:06:20.749604+00:00
[2025-07-09T20:12:18.668+0000] {standard_task_runner.py:60} INFO - Started process 243 to run task
[2025-07-09T20:12:18.674+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-09T20:06:20.749604+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/northwind.py', '--cfg-path', '/tmp/tmpnzqz03qg']
[2025-07-09T20:12:18.679+0000] {standard_task_runner.py:88} INFO - Job 81: Subtask carregamento_postgres
[2025-07-09T20:12:18.762+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:06:20.749604+00:00 [running]> on host 9d65785a077b
[2025-07-09T20:12:18.909+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T20:06:20.749604+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T20:06:20.749604+00:00'
[2025-07-09T20:12:16.650+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-09T20:12:19.433+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-09T20:12:28.732+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:28.724605Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-09T20:12:28.760+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:28.759186Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-09T20:12:28.808+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:28.807217Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-09T20:12:28.856+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:28.855244Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-09T20:12:28.921+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:28.919032Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-09T20:12:28.993+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:28.990735Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-09T20:12:29.058+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:29.056928Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-09T20:12:29.128+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:29.126109Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-09T20:12:37.034+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:36.953872Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-09T20:12:37.082+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:37.003944Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-09T20:12:46.156+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:46.155405Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-09T20:12:46.765+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:46.759614Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-09T20:12:46.860+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:46.859602Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-07-09T20:12:46.862+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:46.861714Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-09T20:12:47.236+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:47.235251Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-07-09T20:12:47.252+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:47.239591Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-09T20:12:46.850+0000] {docker.py:429} INFO - Meltano install completed. Executing command: bash -c meltano config tap-csv-latest set csv_files_definition /opt/meltano/config/tap-csv-latest.json && meltano el tap-csv-latest target-postgres
[2025-07-09T20:12:50.807+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:50.802612Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2025-07-09T20:12:51.221+0000] {docker.py:429} INFO - Extractor 'tap-csv-latest' setting 'csv_files_definition' was set in `meltano.yml`: '/opt/meltano/config/tap-csv-latest.json'
[2025-07-09T20:12:54.255+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:54.254548Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-09T20:12:54.839+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:54.838266Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m
[2025-07-09T20:12:57.457+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.447363Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'order_details'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.461+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.450636Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.667+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.666306Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.669+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.667846Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.672+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.668520Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.674+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.669187Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.675+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.671247Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.949+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.948296Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.950+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.949294Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.952+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.951581Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.954+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.952458Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.956+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.954399Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.956+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.955645Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.958+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.956761Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.958+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.957721Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.959+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.958607Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.960+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.959605Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.963+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.961269Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.965+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.962524Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.967+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.966422Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.968+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.967513Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.969+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.968349Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.970+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.969591Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.971+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.970369Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.971+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.970947Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.972+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.971516Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.973+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.972137Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.974+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.972902Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.975+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.973876Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.976+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.974629Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.977+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.975480Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.978+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.976219Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.979+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.976851Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.979+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.977540Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.980+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.978290Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.981+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.979320Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.981+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.979999Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.982+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.980665Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.984+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.983326Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 96, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.988+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.984369Z[0m [[32m[1minfo     [0m] [1m    attempts = conninfo_attempts(params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:12:57.985007Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/_conninfo_attempts.py", line 53, in conninfo_attempts[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.989+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.985847Z[0m [[32m[1minfo     [0m] [1m    raise e.OperationalError(str(last_exc))[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.990+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.986629Z[0m [[32m[1minfo     [0m] [1mpsycopg.OperationalError: [Errno -2] Name or service not known[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.990+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.987854Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.991+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.988980Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.991+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.989881Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.992+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.990682Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.992+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.991447Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.993+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.992139Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.993+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.992922Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.994+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.993804Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.995+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.994497Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1082, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.996+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.995233Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.997+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.996060Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 98, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.998+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.996851Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:57.999+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.997887Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.001+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:57.999222Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.003+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.001337Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.004+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.003178Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.005+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.004465Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 588, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.006+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.005146Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.007+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.005940Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 775, in listen[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.007+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.006710Z[0m [[32m[1minfo     [0m] [1m    counter = self.process_lines(file_input)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.008+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.007179Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 801, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.009+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.007992Z[0m [[32m[1minfo     [0m] [1m    return self.message_reader.process_lines([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.009+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.008850Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/singerlib/encoding/base.py", line 70, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.010+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.009537Z[0m [[32m[1minfo     [0m] [1m    callback(line_dict)       [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.011+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.010360Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 403, in _process_schema_message[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.012+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.011193Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.013+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.012127Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 817, in get_sink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.014+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.012907Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.015+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.013692Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 751, in add_sqlsink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.016+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.014497Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.016+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.015265Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/target_postgres/sinks.py", line 58, in setup[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.017+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.016464Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema(self.schema_name)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.019+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.017155Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1367, in prepare_schema[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.020+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.018056Z[0m [[32m[1minfo     [0m] [1m    if not self.schema_exists(schema_name):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.020+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.018847Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1200, in schema_exists[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.021+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.020283Z[0m [[32m[1minfo     [0m] [1m    schemas = set(sa.inspect(self._engine).get_schema_names())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.022+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.021453Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 140, in inspect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.024+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.022780Z[0m [[32m[1minfo     [0m] [1m    ret = reg(subject)        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.024+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.023582Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 313, in _engine_insp[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.026+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.024286Z[0m [[32m[1minfo     [0m] [1m    return Inspector._construct(Inspector._init_engine, bind)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.027+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.025916Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 246, in _construct[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.027+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.026730Z[0m [[32m[1minfo     [0m] [1m    init(self, bind)          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.028+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.027484Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 257, in _init_engine[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.029+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.028168Z[0m [[32m[1minfo     [0m] [1m    engine.connect().close()  [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.029+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.028838Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3273, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.030+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.029523Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.031+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.030265Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 147, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.031+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.030828Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.032+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.031425Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.033+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.032045Z[0m [[32m[1minfo     [0m] [1m    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.033+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.032767Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.034+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.033576Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.036+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.034467Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.037+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.035305Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.038+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.036117Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.040+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.037056Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:12:58.038761Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.041+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.039499Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.042+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.040252Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.042+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.041033Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.043+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.041825Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.044+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.042563Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.045+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.043386Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.046+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.044044Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.048+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.044867Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.050+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.046054Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.053+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.047987Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.054+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.048879Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.055+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.049598Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.056+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.050582Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.058+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.051467Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.058+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.052197Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.060+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.052817Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.061+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.053500Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.062+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.054390Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.063+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.054982Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.064+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.055627Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.065+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.056315Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.066+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.057054Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.066+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.058256Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.067+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.059080Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 96, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.067+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.059853Z[0m [[32m[1minfo     [0m] [1m    attempts = conninfo_attempts(params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.068+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.060849Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/_conninfo_attempts.py", line 53, in conninfo_attempts[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.068+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.062177Z[0m [[32m[1minfo     [0m] [1m    raise e.OperationalError(str(last_exc))[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.069+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.062988Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.OperationalError: (psycopg.OperationalError) [Errno -2] Name or service not known[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.069+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.064141Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/20/e3q8)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.170+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.169115Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "timer", "metric": "sync_duration", "value": 0.7208161354064941, "tags": {"stream": "order_details", "pid": 177, "context": {}, "status": "succeeded"}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.171+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.169909Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "counter", "metric": "record_count", "value": 4310, "tags": {"stream": "order_details", "pid": 177, "context": {}}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.172+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.170414Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'public-categories'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.173+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.170907Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.175+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.173335Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "timer", "metric": "sync_duration", "value": 0.0029249191284179688, "tags": {"stream": "public-categories", "pid": 177, "context": {}, "status": "succeeded"}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.176+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.174663Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "counter", "metric": "record_count", "value": 16, "tags": {"stream": "public-categories", "pid": 177, "context": {}}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.176+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.175651Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'public-customers'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.177+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.176338Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.210+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.209232Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "timer", "metric": "sync_duration", "value": 0.03394174575805664, "tags": {"stream": "public-customers", "pid": 177, "context": {}, "status": "succeeded"}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.211+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.210121Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "counter", "metric": "record_count", "value": 182, "tags": {"stream": "public-customers", "pid": 177, "context": {}}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.211+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.210605Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'public-employee_territories'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.212+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.211084Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.226+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.225776Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "timer", "metric": "sync_duration", "value": 0.015602588653564453, "tags": {"stream": "public-employee_territories", "pid": 177, "context": {}, "status": "succeeded"}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.227+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.226524Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "counter", "metric": "record_count", "value": 98, "tags": {"stream": "public-employee_territories", "pid": 177, "context": {}}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.227+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.227088Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'public-employees'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.228+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.227741Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.234+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.233249Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "timer", "metric": "sync_duration", "value": 0.0043294429779052734, "tags": {"stream": "public-employees", "pid": 177, "context": {}, "status": "succeeded"}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.235+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.234090Z[0m [[32m[1minfo     [0m] [1mMETRIC: {"type": "counter", "metric": "record_count", "value": 18, "tags": {"stream": "public-employees", "pid": 177, "context": {}}}[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.235+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.235151Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'public-orders'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.236+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.235633Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m8228632a-160f-49d6-b616-d2de86354449[0m [36mstate_id[0m=[35m2025-07-09T201254--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:12:58.837+0000] {docker.py:429} INFO - [2m2025-07-09T20:12:58.236838Z[0m [[31m[1merror    [0m] [1m                              [0m
[31m╭─[0m[31m────────────────────[0m[31m [0m[1;31mTraceback [0m[1;2;31m(most recent call last)[0m[31m [0m[31m─────────────────────[0m[31m─╮[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1moutput_logger.py[0m:217  [31m│[0m
[31m│[0m in redirect_logging                                                          [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m214 [0m[2m│   │   │   [0m*ignore_errors,                                            [31m│[0m
[31m│[0m   [2m215 [0m[2m│   │   [0m)                                                              [31m│[0m
[31m│[0m   [2m216 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m [31m❱ [0m217 [2m│   │   │   [0m[94myield[0m                                                      [31m│[0m
[31m│[0m   [2m218 [0m[2m│   │   [0m[94mexcept[0m ignored_errors:                                         [31m│[0m
[31m│[0m   [2m219 [0m[2m│   │   │   [0m[94mraise[0m                                                      [31m│[0m
[31m│[0m   [2m220 [0m[2m│   │   [0m[94mexcept[0m RunnerError [94mas[0m err:                                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:475 in _redirect_output [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m472 [0m[2m│   [0m[94mwith[0m meltano_stdout.redirect_logging(ignore_errors=(CliError,)):   [31m│[0m
[31m│[0m   [2m473 [0m[2m│   │   [0m[94masync[0m [94mwith[0m meltano_stdout.redirect_stdout(), meltano_stderr.re [31m│[0m
[31m│[0m   [2m474 [0m[2m│   │   │   [0m[94mtry[0m:                                                       [31m│[0m
[31m│[0m [31m❱ [0m475 [2m│   │   │   │   [0m[94myield[0m                                                  [31m│[0m
[31m│[0m   [2m476 [0m[2m│   │   │   [0m[94mexcept[0m CliError [94mas[0m err:                                    [31m│[0m
[31m│[0m   [2m477 [0m[2m│   │   │   │   [0merr.print()                                            [31m│[0m
[31m│[0m   [2m478 [0m[2m│   │   │   │   [0m[94mraise[0m                                                  [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:508 in _run_elt         [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m505 [0m[2m│   │   │   [0m[94mif[0m elt_context.only_transform:                             [31m│[0m
[31m│[0m   [2m506 [0m[2m│   │   │   │   [0mlog.info([33m"[0m[33mExtract & load skipped.[0m[33m"[0m)                    [31m│[0m
[31m│[0m   [2m507 [0m[2m│   │   │   [0m[94melse[0m:                                                      [31m│[0m
[31m│[0m [31m❱ [0m508 [2m│   │   │   │   [0m[94mawait[0m _run_extract_load(log, elt_context, output_logge [31m│[0m
[31m│[0m   [2m509 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m510 [0m[2m│   │   │   [0m[94mif[0m elt_context.transformer:                                [31m│[0m
[31m│[0m   [2m511 [0m[2m│   │   │   │   [0mlog.warning(                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:581 in                  [31m│[0m
[31m│[0m _run_extract_load                                                            [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m578 [0m[2m│   │   │   [0m[94mwith[0m loader_log.line_writer() [94mas[0m loader_log_writer:        [31m│[0m
[31m│[0m   [2m579 [0m[2m│   │   │   │   [0m[94mwith[0m extractor_out_writer_ctxmgr() [94mas[0m extractor_out_wr [31m│[0m
[31m│[0m   [2m580 [0m[2m│   │   │   │   │   [0m[94mwith[0m loader_out_writer_ctxmgr() [94mas[0m loader_out_writ [31m│[0m
[31m│[0m [31m❱ [0m581 [2m│   │   │   │   │   │   [0m[94mawait[0m singer_runner.run(                       [31m│[0m
[31m│[0m   [2m582 [0m[2m│   │   │   │   │   │   │   [0m**kwargs,                                  [31m│[0m
[31m│[0m   [2m583 [0m[2m│   │   │   │   │   │   │   [0mextractor_log=extractor_log_writer,        [31m│[0m
[31m│[0m   [2m584 [0m[2m│   │   │   │   │   │   │   [0mloader_log=loader_log_writer,              [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:229 in run   [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m226 [0m[2m│   │   │   [0mtap.prepared([96mself[0m.context.session),                        [31m│[0m
[31m│[0m   [2m227 [0m[2m│   │   │   [0mtarget.prepared([96mself[0m.context.session),                     [31m│[0m
[31m│[0m   [2m228 [0m[2m│   │   [0m):                                                             [31m│[0m
[31m│[0m [31m❱ [0m229 [2m│   │   │   [0m[94mawait[0m [96mself[0m.invoke(  [2m# noqa: RET503[0m                         [31m│[0m
[31m│[0m   [2m230 [0m[2m│   │   │   │   [0mtap,                                                   [31m│[0m
[31m│[0m   [2m231 [0m[2m│   │   │   │   [0mtarget,                                                [31m│[0m
[31m│[0m   [2m232 [0m[2m│   │   │   │   [0mextractor_log=extractor_log,                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:148 in       [31m│[0m
[31m│[0m invoke                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m145 [0m[2m│   │   │   │   │   [0m)                                                  [31m│[0m
[31m│[0m   [2m146 [0m[2m│   │   │   │   [0m                                                       [31m│[0m
[31m│[0m   [2m147 [0m[2m│   │   │   │   [0mfailed_future = output_futures_failed.pop()            [31m│[0m
[31m│[0m [31m❱ [0m148 [2m│   │   │   │   [0m[94mraise[0m failed_future.exception()                        [31m│[0m
[31m│[0m   [2m149 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m150 [0m[2m│   │   │   [0m[2m# If all of the output handlers completed without raising [0m [31m│[0m
[31m│[0m   [2m151 [0m[2m│   │   │   [0m[2m# exception, we still need to wait for the tap or target t[0m [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:305 in       [31m│[0m
[31m│[0m capture_subprocess_output                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m302 [0m[2m│   │   │   [0m[94mcontinue[0m                                                   [31m│[0m
[31m│[0m   [2m303 [0m[2m│   │   [0m                                                               [31m│[0m
[31m│[0m   [2m304 [0m[2m│   │   [0m[94mfor[0m writer [95min[0m line_writers:                                    [31m│[0m
[31m│[0m [31m❱ [0m305 [2m│   │   │   [0m[94mif[0m [95mnot[0m [94mawait[0m _write_line_writer(writer, line):             [31m│[0m
[31m│[0m   [2m306 [0m[2m│   │   │   │   [0m[2m# If the destination stream is closed, we can stop cap[0m [31m│[0m
[31m│[0m   [2m307 [0m[2m│   │   │   │   [0m[94mreturn[0m                                                 [31m│[0m
[31m│[0m   [2m308 [0m                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:273 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m   [2m271 [0m[2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m [31m❱ [0m273 [2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m   [2m275 [0m[2m│   [0m[94melse[0m:                                                              [31m│[0m
[31m│[0m   [2m276 [0m[2m│   │   [0mwriter.writeline(line.decode(errors=[33m"[0m[33mreplace[0m[33m"[0m))                [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:359 in wait_closed               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m356 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.is_closing()                            [31m│[0m
[31m│[0m   [2m357 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m358 [0m[2m│   [0m[94masync[0m [94mdef[0m[90m [0m[92mwait_closed[0m([96mself[0m):                                       [31m│[0m
[31m│[0m [31m❱ [0m359 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._get_close_waiter([96mself[0m)                   [31m│[0m
[31m│[0m   [2m360 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m361 [0m[2m│   [0m[94mdef[0m[90m [0m[92mget_extra_info[0m([96mself[0m, name, default=[94mNone[0m):                      [31m│[0m
[31m│[0m   [2m362 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.get_extra_info(name, default)           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:271 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m268 [0m[2m│   [0m[94mif[0m [96misinstance[0m(writer, asyncio.StreamWriter):                       [31m│[0m
[31m│[0m   [2m269 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m [31m❱ [0m271 [2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m   [2m273 [0m[2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:387 in drain                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m384 [0m[2m│   │   │   [0m[2m# in a loop would never call connection_lost(), so it[0m      [31m│[0m
[31m│[0m   [2m385 [0m[2m│   │   │   [0m[2m# would not see an error when the socket is closed.[0m        [31m│[0m
[31m│[0m   [2m386 [0m[2m│   │   │   [0m[94mawait[0m sleep([94m0[0m)                                             [31m│[0m
[31m│[0m [31m❱ [0m387 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._drain_helper()                           [31m│[0m
[31m│[0m   [2m388 [0m                                                                       [31m│[0m
[31m│[0m   [2m389 [0m                                                                       [31m│[0m
[31m│[0m   [2m390 [0m[94mclass[0m[90m [0m[4;92mStreamReader[0m:                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:197 in _drain_helper             [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m194 [0m[2m│   │   [0m[94massert[0m waiter [95mis[0m [94mNone[0m [95mor[0m waiter.cancelled()                    [31m│[0m
[31m│[0m   [2m195 [0m[2m│   │   [0mwaiter = [96mself[0m._loop.create_future()                            [31m│[0m
[31m│[0m   [2m196 [0m[2m│   │   [0m[96mself[0m._drain_waiter = waiter                                    [31m│[0m
[31m│[0m [31m❱ [0m197 [2m│   │   [0m[94mawait[0m waiter                                                   [31m│[0m
[31m│[0m   [2m198 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m199 [0m[2m│   [0m[94mdef[0m[90m [0m[92m_get_close_waiter[0m([96mself[0m, stream):                               [31m│[0m
[31m│[0m   [2m200 [0m[2m│   │   [0m[94mraise[0m [96mNotImplementedError[0m                                      [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────╯[0m
[1;91mBrokenPipeError[0m
[2025-07-09T20:12:58.855+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.
[2025-07-09T20:13:00.831+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-09T20:13:00.848+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250709T200620, start_date=20250709T201218, end_date=20250709T201300
[2025-07-09T20:13:00.952+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-09T20:13:00.955+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-09T20:13:00.955+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-09T20:13:00.972+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-09T20:13:00.972+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-09T20:13:00.974+0000] {taskinstance.py:826} ERROR - Failed to send email to: ['lrbf@cin.ufpe.br']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2499, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2516, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1000, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 824, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2946, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1002, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-09T20:13:01.008+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 81 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 243)
[2025-07-09T20:13:01.066+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-09T20:13:01.128+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
