[2025-07-01T21:48:50.573+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-01T21:42:40.684961+00:00 [queued]>
[2025-07-01T21:48:50.583+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-01T21:42:40.684961+00:00 [queued]>
[2025-07-01T21:48:50.584+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-01T21:48:50.597+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-01 21:42:40.684961+00:00
[2025-07-01T21:48:50.603+0000] {standard_task_runner.py:60} INFO - Started process 248 to run task
[2025-07-01T21:48:50.609+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-01T21:42:40.684961+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/northwind.py', '--cfg-path', '/tmp/tmpytre8i_h']
[2025-07-01T21:48:50.617+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask carregamento_postgres
[2025-07-01T21:48:50.709+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-01T21:42:40.684961+00:00 [running]> on host e62fc41f1c39
[2025-07-01T21:48:50.809+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T21:42:40.684961+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-01T21:42:40.684961+00:00'
[2025-07-01T21:48:50.910+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-01T21:48:51.328+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-01T21:48:52.994+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:52.993882Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-01T21:48:53.004+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:53.003457Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-01T21:48:53.021+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:53.020530Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-01T21:48:53.037+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:53.036834Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-01T21:48:53.053+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:53.052550Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-01T21:48:53.076+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:53.075436Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-01T21:48:53.102+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:53.101976Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-01T21:48:53.134+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:53.133834Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-01T21:48:54.193+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:54.192190Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-01T21:48:54.198+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:54.197657Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-01T21:48:59.068+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:59.067532Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-07-01T21:48:59.165+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:59.164690Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-01T21:48:59.944+0000] {docker.py:429} INFO - [2m2025-07-01T21:48:59.943778Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-01T21:49:00.074+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:00.074294Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-01T21:49:00.077+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:00.077177Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2m2025-07-01T21:49:00.077424Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-01T21:49:00.838+0000] {docker.py:429} INFO - Meltano install completed. Executing command: meltano el tap-csv-latest --catalog /opt/meltano/config/tap-csv-latest.json target-postgres
[2025-07-01T21:49:01.966+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:01.965595Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-01T21:49:02.342+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:02.341954Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m
[2025-07-01T21:49:02.464+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:02.463695Z[0m [[32m[1minfo     [0m] [1mUsing custom catalog in /opt/meltano/config/tap-csv-latest.json[0m
[2025-07-01T21:49:02.466+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:02.465803Z[0m [[33m[1mwarning  [0m] [1mA catalog file was found, but it will be ignored as the extractor does not advertise the `catalog` or `properties` capability[0m
[2025-07-01T21:49:03.035+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.034246Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.035+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.034920Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/bin/tap-csv", line 8, in <module>[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.035+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.035193Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TapCSV.cli())    [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.036+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.035424Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.036+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.035792Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.036+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.036071Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/click/core.py", line 1082, in main[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.036+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.036323Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.037+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.036568Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 93, in invoke[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.037+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.036821Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.037+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.037065Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.037+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.037317Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.037+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.037580Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.038+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.037830Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.038+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.038217Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 516, in invoke[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.038+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.038527Z[0m [[32m[1minfo     [0m] [1m    tap = cls(                [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.039+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.038838Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 118, in __init__[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.039+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.039085Z[0m [[32m[1minfo     [0m] [1m    self.setup_mapper()       [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.039+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.039341Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 194, in setup_mapper[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.039+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.039590Z[0m [[32m[1minfo     [0m] [1m    self.mapper.register_raw_streams_from_catalog(self.catalog)[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.040+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.039843Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 187, in catalog[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.040+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.040084Z[0m [[32m[1minfo     [0m] [1m    self._catalog = self.input_catalog or self._singer_catalog[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.040+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.040331Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 340, in _singer_catalog[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.040+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.040611Z[0m [[32m[1minfo     [0m] [1m    for stream in self.streams.values()[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.041+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.040835Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 149, in streams[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.041+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.041056Z[0m [[32m[1minfo     [0m] [1m    for stream in self.load_streams():[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.041+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.041238Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 373, in load_streams[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.041+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.041425Z[0m [[32m[1minfo     [0m] [1m    for stream in self.discover_streams():[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.042+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.041668Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/tap_csv/tap.py", line 89, in discover_streams[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.042+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.041889Z[0m [[32m[1minfo     [0m] [1m    return [                  [0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.042+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.042176Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/extractors/tap-csv-latest/venv/lib/python3.9/site-packages/tap_csv/tap.py", line 92, in <listcomp>[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.042+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.042469Z[0m [[32m[1minfo     [0m] [1m    name=file_config.get("entity"),[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.043+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.042723Z[0m [[32m[1minfo     [0m] [1mAttributeError: 'str' object has no attribute 'get'[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.141+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.140490Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.142+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.141730Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-01T21:49:03.141992Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.142+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.142151Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.142+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.142350Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.142+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.142629Z[0m [[32m[1minfo     [0m] [1mThe `dialect+driver` configuration option is deprecated. Please set it to `postgresql+psycopg`, as this will be the hard-coded value in the future.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.143+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.142847Z[0m [[32m[1minfo     [0m] [1mReader 'target-postgres' completed processing 0 lines of input (0 schemas, 0 records, 0 batch manifests, 0 state messages, 0 activate version messages).[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.214+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.213544Z[0m [[31m[1merror    [0m] [1mExtraction failed             [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m"AttributeError: 'str' object has no attribute 'get'"[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m
[2025-07-01T21:49:03.214+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.214213Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Extractor failed.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.214+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.214396Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.214+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.214622Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-07-01T214902--tap-csv-latest--target-postgres/e71ada73-47d7-44b1-a4e3-c0816aa61577/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.215+0000] {docker.py:429} INFO - [2m2025-07-01T21:49:03.214787Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35me71ada73-47d7-44b1-a4e3-c0816aa61577[0m [36mstate_id[0m=[35m2025-07-01T214902--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T21:49:03.227+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

ELT could not be completed: Extractor failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-07-01T214902--tap-csv-latest--target-postgres/e71ada73-47d7-44b1-a4e3-c0816aa61577/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2025-07-01T21:49:04.344+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T21:49:04.348+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250701T214240, start_date=20250701T214850, end_date=20250701T214904
[2025-07-01T21:49:04.408+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-01T21:49:04.409+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-01T21:49:04.409+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-01T21:49:04.428+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-01T21:49:04.429+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-01T21:49:04.430+0000] {taskinstance.py:826} ERROR - Failed to send email to: ['lrbf@cin.ufpe.br']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2499, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2516, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1000, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 824, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2946, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1002, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-01T21:49:04.449+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 248)
[2025-07-01T21:49:04.486+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-01T21:49:04.500+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
