[2025-07-09T20:46:26.099+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:45:38.869934+00:00 [queued]>
[2025-07-09T20:46:26.106+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:45:38.869934+00:00 [queued]>
[2025-07-09T20:46:26.106+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-09T20:46:26.116+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-09 20:45:38.869934+00:00
[2025-07-09T20:46:26.121+0000] {standard_task_runner.py:60} INFO - Started process 411 to run task
[2025-07-09T20:46:26.124+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-09T20:45:38.869934+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/northwind.py', '--cfg-path', '/tmp/tmp0i02oztd']
[2025-07-09T20:46:26.126+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask carregamento_postgres
[2025-07-09T20:46:26.169+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:45:38.869934+00:00 [running]> on host 9d65785a077b
[2025-07-09T20:46:26.240+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T20:45:38.869934+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T20:45:38.869934+00:00'
[2025-07-09T20:46:26.291+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-09T20:46:26.549+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-09T20:46:27.762+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:27.761587Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-09T20:46:27.773+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:27.773048Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-09T20:46:27.792+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:27.791596Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-09T20:46:27.811+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:27.811053Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-09T20:46:27.836+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:27.835449Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-09T20:46:27.858+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:27.857674Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-09T20:46:27.924+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:27.923629Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-09T20:46:27.972+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:27.971382Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-09T20:46:29.004+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:29.003530Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-09T20:46:29.064+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:29.063859Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-09T20:46:29.884+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:29.882974Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-09T20:46:30.420+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:30.420300Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-09T20:46:30.742+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:30.741962Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-07-09T20:46:30.801+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:30.800642Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-09T20:46:30.857+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:30.856601Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2m2025-07-09T20:46:30.856899Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-09T20:46:31.674+0000] {docker.py:429} INFO - Meltano install completed. Executing command: bash -c meltano config tap-csv-latest set csv_files_definition /opt/meltano/config/tap-csv-latest.json && meltano el tap-csv-latest target-postgres
[2025-07-09T20:46:32.745+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:32.744885Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2025-07-09T20:46:32.943+0000] {docker.py:429} INFO - Extractor 'tap-csv-latest' setting 'csv_files_definition' was set in `meltano.yml`: '/opt/meltano/config/tap-csv-latest.json'
[2025-07-09T20:46:34.809+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:34.808615Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-09T20:46:35.155+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:35.154347Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m
[2025-07-09T20:46:35.807+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:35.806679Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'order_details'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:35.808+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:35.807230Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:35.906+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:35.904469Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:35.906+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:35.906140Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:35.907+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:35.906674Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:35.907+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:35.907299Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:35.909+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:35.908139Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.018+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.017701Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.018001Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.018+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.018198Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.019+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.018457Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.020+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.019673Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.020+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.019972Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.021+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.020391Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.021+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.020864Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.023+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.022105Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.024+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.022492Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.024+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.023790Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.025+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.024539Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.026+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.025701Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.026+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.026046Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.026+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.026337Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.027+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.026760Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.027+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.027329Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.028+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.027669Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.032+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.027941Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.028269Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.028519Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.028728Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.028976Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.029226Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.029446Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.029652Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.029865Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.030108Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.030610Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.031221Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.033+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.031655Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.032035Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 125, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.032325Z[0m [[32m[1minfo     [0m] [1m    raise type(last_ex)("\n".join(lines)).with_traceback(None)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.032550Z[0m [[32m[1minfo     [0m] [1mpsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.032743Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.037+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.032955Z[0m [[32m[1minfo     [0m] [1mMultiple connection attempts failed. All failures were:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.033206Z[0m [[32m[1minfo     [0m] [1m- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.033439Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.033661Z[0m [[32m[1minfo     [0m] [1m- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.033847Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.033993Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.034131Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.034267Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.034407Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.034542Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.034679Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.034818Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.034962Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.035097Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1082, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.035234Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.035371Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 98, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.037+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.035707Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.035972Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.036225Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.036455Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.036708Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.038+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.036959Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 588, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.038+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.037207Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.038+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.037463Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 775, in listen[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.038+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.037720Z[0m [[32m[1minfo     [0m] [1m    counter = self.process_lines(file_input)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.039+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.037946Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 801, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.039+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.038211Z[0m [[32m[1minfo     [0m] [1m    return self.message_reader.process_lines([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.039+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.038483Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/singerlib/encoding/base.py", line 70, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.039+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.038945Z[0m [[32m[1minfo     [0m] [1m    callback(line_dict)       [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.039+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.039343Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 403, in _process_schema_message[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.040+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.039735Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.040+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.040056Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 817, in get_sink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.040+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.040380Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.041+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.040655Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 751, in add_sqlsink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.041+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.040913Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.041+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.041181Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/target_postgres/sinks.py", line 58, in setup[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.041+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.041453Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema(self.schema_name)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.042+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.041721Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1367, in prepare_schema[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.042+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.041968Z[0m [[32m[1minfo     [0m] [1m    if not self.schema_exists(schema_name):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.042+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.042314Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1200, in schema_exists[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.042+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.042620Z[0m [[32m[1minfo     [0m] [1m    schemas = set(sa.inspect(self._engine).get_schema_names())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.043+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.042922Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 140, in inspect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.043+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.043198Z[0m [[32m[1minfo     [0m] [1m    ret = reg(subject)        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.044+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.043514Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 313, in _engine_insp[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.044+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.043807Z[0m [[32m[1minfo     [0m] [1m    return Inspector._construct(Inspector._init_engine, bind)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.044+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.044068Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 246, in _construct[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.044+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.044336Z[0m [[32m[1minfo     [0m] [1m    init(self, bind)          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.045+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.044663Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 257, in _init_engine[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.045+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.045054Z[0m [[32m[1minfo     [0m] [1m    engine.connect().close()  [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.045+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.045340Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3273, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.046+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.045787Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.046+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.046063Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 147, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.046+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.046302Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.047+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.046784Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.047+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.047101Z[0m [[32m[1minfo     [0m] [1m    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.047+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.047507Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.048+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.047837Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.048+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.048177Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.049+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.048553Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.049+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.049356Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.050+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.049860Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.050+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.050167Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.050+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.050462Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.051+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.050797Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.051+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.051076Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.051+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.051346Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.052+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.051647Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.052+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.051909Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:46:36.052193Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.053+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.052493Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.053+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.052738Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.053+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.053014Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.054+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.053323Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.054+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.053609Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.054+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.053911Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.054+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.054165Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.055+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.054444Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.055+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.054781Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.055+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.055053Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.055+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.055330Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.056+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.055630Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.056+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.055918Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.056+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.056191Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.057+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.056450Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.057+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.056713Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.058+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.056963Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 125, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.058+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.057190Z[0m [[32m[1minfo     [0m] [1m    raise type(last_ex)("\n".join(lines)).with_traceback(None)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.058+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.057419Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.058+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.057689Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.059+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.057950Z[0m [[32m[1minfo     [0m] [1mMultiple connection attempts failed. All failures were:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.059+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.058208Z[0m [[32m[1minfo     [0m] [1m- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.059+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.058475Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.059+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.058745Z[0m [[32m[1minfo     [0m] [1m- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.060+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.059020Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.060+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.059301Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/20/e3q8)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m3bcdea0c-25e4-411e-bdf4-dba2df1ad0a9[0m [36mstate_id[0m=[35m2025-07-09T204634--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:46:36.520+0000] {docker.py:429} INFO - [2m2025-07-09T20:46:36.166640Z[0m [[31m[1merror    [0m] [1m                              [0m
[31m╭─[0m[31m────────────────────[0m[31m [0m[1;31mTraceback [0m[1;2;31m(most recent call last)[0m[31m [0m[31m─────────────────────[0m[31m─╮[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1moutput_logger.py[0m:217  [31m│[0m
[31m│[0m in redirect_logging                                                          [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m214 [0m[2m│   │   │   [0m*ignore_errors,                                            [31m│[0m
[31m│[0m   [2m215 [0m[2m│   │   [0m)                                                              [31m│[0m
[31m│[0m   [2m216 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m [31m❱ [0m217 [2m│   │   │   [0m[94myield[0m                                                      [31m│[0m
[31m│[0m   [2m218 [0m[2m│   │   [0m[94mexcept[0m ignored_errors:                                         [31m│[0m
[31m│[0m   [2m219 [0m[2m│   │   │   [0m[94mraise[0m                                                      [31m│[0m
[31m│[0m   [2m220 [0m[2m│   │   [0m[94mexcept[0m RunnerError [94mas[0m err:                                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:475 in _redirect_output [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m472 [0m[2m│   [0m[94mwith[0m meltano_stdout.redirect_logging(ignore_errors=(CliError,)):   [31m│[0m
[31m│[0m   [2m473 [0m[2m│   │   [0m[94masync[0m [94mwith[0m meltano_stdout.redirect_stdout(), meltano_stderr.re [31m│[0m
[31m│[0m   [2m474 [0m[2m│   │   │   [0m[94mtry[0m:                                                       [31m│[0m
[31m│[0m [31m❱ [0m475 [2m│   │   │   │   [0m[94myield[0m                                                  [31m│[0m
[31m│[0m   [2m476 [0m[2m│   │   │   [0m[94mexcept[0m CliError [94mas[0m err:                                    [31m│[0m
[31m│[0m   [2m477 [0m[2m│   │   │   │   [0merr.print()                                            [31m│[0m
[31m│[0m   [2m478 [0m[2m│   │   │   │   [0m[94mraise[0m                                                  [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:508 in _run_elt         [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m505 [0m[2m│   │   │   [0m[94mif[0m elt_context.only_transform:                             [31m│[0m
[31m│[0m   [2m506 [0m[2m│   │   │   │   [0mlog.info([33m"[0m[33mExtract & load skipped.[0m[33m"[0m)                    [31m│[0m
[31m│[0m   [2m507 [0m[2m│   │   │   [0m[94melse[0m:                                                      [31m│[0m
[31m│[0m [31m❱ [0m508 [2m│   │   │   │   [0m[94mawait[0m _run_extract_load(log, elt_context, output_logge [31m│[0m
[31m│[0m   [2m509 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m510 [0m[2m│   │   │   [0m[94mif[0m elt_context.transformer:                                [31m│[0m
[31m│[0m   [2m511 [0m[2m│   │   │   │   [0mlog.warning(                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:581 in                  [31m│[0m
[31m│[0m _run_extract_load                                                            [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m578 [0m[2m│   │   │   [0m[94mwith[0m loader_log.line_writer() [94mas[0m loader_log_writer:        [31m│[0m
[31m│[0m   [2m579 [0m[2m│   │   │   │   [0m[94mwith[0m extractor_out_writer_ctxmgr() [94mas[0m extractor_out_wr [31m│[0m
[31m│[0m   [2m580 [0m[2m│   │   │   │   │   [0m[94mwith[0m loader_out_writer_ctxmgr() [94mas[0m loader_out_writ [31m│[0m
[31m│[0m [31m❱ [0m581 [2m│   │   │   │   │   │   [0m[94mawait[0m singer_runner.run(                       [31m│[0m
[31m│[0m   [2m582 [0m[2m│   │   │   │   │   │   │   [0m**kwargs,                                  [31m│[0m
[31m│[0m   [2m583 [0m[2m│   │   │   │   │   │   │   [0mextractor_log=extractor_log_writer,        [31m│[0m
[31m│[0m   [2m584 [0m[2m│   │   │   │   │   │   │   [0mloader_log=loader_log_writer,              [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:229 in run   [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m226 [0m[2m│   │   │   [0mtap.prepared([96mself[0m.context.session),                        [31m│[0m
[31m│[0m   [2m227 [0m[2m│   │   │   [0mtarget.prepared([96mself[0m.context.session),                     [31m│[0m
[31m│[0m   [2m228 [0m[2m│   │   [0m):                                                             [31m│[0m
[31m│[0m [31m❱ [0m229 [2m│   │   │   [0m[94mawait[0m [96mself[0m.invoke(  [2m# noqa: RET503[0m                         [31m│[0m
[31m│[0m   [2m230 [0m[2m│   │   │   │   [0mtap,                                                   [31m│[0m
[31m│[0m   [2m231 [0m[2m│   │   │   │   [0mtarget,                                                [31m│[0m
[31m│[0m   [2m232 [0m[2m│   │   │   │   [0mextractor_log=extractor_log,                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:148 in       [31m│[0m
[31m│[0m invoke                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m145 [0m[2m│   │   │   │   │   [0m)                                                  [31m│[0m
[31m│[0m   [2m146 [0m[2m│   │   │   │   [0m                                                       [31m│[0m
[31m│[0m   [2m147 [0m[2m│   │   │   │   [0mfailed_future = output_futures_failed.pop()            [31m│[0m
[31m│[0m [31m❱ [0m148 [2m│   │   │   │   [0m[94mraise[0m failed_future.exception()                        [31m│[0m
[31m│[0m   [2m149 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m150 [0m[2m│   │   │   [0m[2m# If all of the output handlers completed without raising [0m [31m│[0m
[31m│[0m   [2m151 [0m[2m│   │   │   [0m[2m# exception, we still need to wait for the tap or target t[0m [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:305 in       [31m│[0m
[31m│[0m capture_subprocess_output                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m302 [0m[2m│   │   │   [0m[94mcontinue[0m                                                   [31m│[0m
[31m│[0m   [2m303 [0m[2m│   │   [0m                                                               [31m│[0m
[31m│[0m   [2m304 [0m[2m│   │   [0m[94mfor[0m writer [95min[0m line_writers:                                    [31m│[0m
[31m│[0m [31m❱ [0m305 [2m│   │   │   [0m[94mif[0m [95mnot[0m [94mawait[0m _write_line_writer(writer, line):             [31m│[0m
[31m│[0m   [2m306 [0m[2m│   │   │   │   [0m[2m# If the destination stream is closed, we can stop cap[0m [31m│[0m
[31m│[0m   [2m307 [0m[2m│   │   │   │   [0m[94mreturn[0m                                                 [31m│[0m
[31m│[0m   [2m308 [0m                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:273 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m   [2m271 [0m[2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m [31m❱ [0m273 [2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m   [2m275 [0m[2m│   [0m[94melse[0m:                                                              [31m│[0m
[31m│[0m   [2m276 [0m[2m│   │   [0mwriter.writeline(line.decode(errors=[33m"[0m[33mreplace[0m[33m"[0m))                [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:359 in wait_closed               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m356 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.is_closing()                            [31m│[0m
[31m│[0m   [2m357 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m358 [0m[2m│   [0m[94masync[0m [94mdef[0m[90m [0m[92mwait_closed[0m([96mself[0m):                                       [31m│[0m
[31m│[0m [31m❱ [0m359 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._get_close_waiter([96mself[0m)                   [31m│[0m
[31m│[0m   [2m360 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m361 [0m[2m│   [0m[94mdef[0m[90m [0m[92mget_extra_info[0m([96mself[0m, name, default=[94mNone[0m):                      [31m│[0m
[31m│[0m   [2m362 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.get_extra_info(name, default)           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:271 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m268 [0m[2m│   [0m[94mif[0m [96misinstance[0m(writer, asyncio.StreamWriter):                       [31m│[0m
[31m│[0m   [2m269 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m [31m❱ [0m271 [2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m   [2m273 [0m[2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:387 in drain                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m384 [0m[2m│   │   │   [0m[2m# in a loop would never call connection_lost(), so it[0m      [31m│[0m
[31m│[0m   [2m385 [0m[2m│   │   │   [0m[2m# would not see an error when the socket is closed.[0m        [31m│[0m
[31m│[0m   [2m386 [0m[2m│   │   │   [0m[94mawait[0m sleep([94m0[0m)                                             [31m│[0m
[31m│[0m [31m❱ [0m387 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._drain_helper()                           [31m│[0m
[31m│[0m   [2m388 [0m                                                                       [31m│[0m
[31m│[0m   [2m389 [0m                                                                       [31m│[0m
[31m│[0m   [2m390 [0m[94mclass[0m[90m [0m[4;92mStreamReader[0m:                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:197 in _drain_helper             [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m194 [0m[2m│   │   [0m[94massert[0m waiter [95mis[0m [94mNone[0m [95mor[0m waiter.cancelled()                    [31m│[0m
[31m│[0m   [2m195 [0m[2m│   │   [0mwaiter = [96mself[0m._loop.create_future()                            [31m│[0m
[31m│[0m   [2m196 [0m[2m│   │   [0m[96mself[0m._drain_waiter = waiter                                    [31m│[0m
[31m│[0m [31m❱ [0m197 [2m│   │   [0m[94mawait[0m waiter                                                   [31m│[0m
[31m│[0m   [2m198 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m199 [0m[2m│   [0m[94mdef[0m[90m [0m[92m_get_close_waiter[0m([96mself[0m, stream):                               [31m│[0m
[31m│[0m   [2m200 [0m[2m│   │   [0m[94mraise[0m [96mNotImplementedError[0m                                      [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────╯[0m
[1;91mBrokenPipeError[0m
[2025-07-09T20:46:36.535+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.
[2025-07-09T20:46:37.599+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-09T20:46:37.604+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250709T204538, start_date=20250709T204626, end_date=20250709T204637
[2025-07-09T20:46:37.622+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 91 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 411)
[2025-07-09T20:46:37.667+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-09T20:46:37.688+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
