[2025-06-25T20:12:50.397+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-25T20:12:05.237784+00:00 [queued]>
[2025-06-25T20:12:50.405+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-25T20:12:05.237784+00:00 [queued]>
[2025-06-25T20:12:50.405+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-25T20:12:50.416+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-06-25 20:12:05.237784+00:00
[2025-06-25T20:12:50.420+0000] {standard_task_runner.py:60} INFO - Started process 186 to run task
[2025-06-25T20:12:50.423+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-06-25T20:12:05.237784+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsqtn_7qp']
[2025-06-25T20:12:50.425+0000] {standard_task_runner.py:88} INFO - Job 133: Subtask carregamento_postgres
[2025-06-25T20:12:50.469+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-06-25T20:12:05.237784+00:00 [running]> on host 6afc1f3750fb
[2025-06-25T20:12:50.536+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T20:12:05.237784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T20:12:05.237784+00:00'
[2025-06-25T20:12:50.577+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-06-25T20:12:50.831+0000] {docker.py:429} INFO - Running meltano install...
[2025-06-25T20:12:51.895+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:51.894847Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-06-25T20:12:51.904+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:51.904222Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-06-25T20:12:51.915+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:51.915029Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-06-25T20:12:51.927+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:51.927260Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-06-25T20:12:51.947+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:51.947101Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-06-25T20:12:51.960+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:51.959560Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-06-25T20:12:51.981+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:51.980590Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-06-25T20:12:52.007+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:52.000365Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-06-25T20:12:53.253+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:53.252765Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-06-25T20:12:53.263+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:53.263385Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-06-25T20:12:58.376+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:58.375280Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-06-25T20:12:58.448+0000] {docker.py:429} INFO - [2m2025-06-25T20:12:58.447834Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-06-25T20:13:00.843+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:00.843006Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-06-25T20:13:00.967+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:00.966612Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-06-25T20:13:01.081+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:01.080698Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2m2025-06-25T20:13:01.080969Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-06-25T20:13:02.062+0000] {docker.py:429} INFO - Meltano install completed. Executing command: meltano el tap-csv-latest target-postgres
[2025-06-25T20:13:03.290+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:03.289948Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-06-25T20:13:03.815+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:03.814224Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m
[2025-06-25T20:13:04.762+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.761736Z[0m [[32m[1minfo     [0m] [1mConfig validation error: '/opt/meltano/config/tap-csv-latest.json' is not of type 'array', 'null' in config['files'][0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.918+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.917385Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.2[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.918+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.917779Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.919+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.918077Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.919+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.918328Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.919+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.918627Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.919+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.918988Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1442, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.920+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.919555Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.920+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.919880Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1363, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.920+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.920236Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.921+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.920501Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/plugin_base.py", line 97, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.921+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.920831Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.921+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.921158Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1226, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.922+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.921487Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.922+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.921812Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 794, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.922+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.922241Z[0m [[32m[1minfo     [0m] [1m    return callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.923+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.922505Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 583, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.923+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.922863Z[0m [[32m[1minfo     [0m] [1m    target = cls(             [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.923+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.923142Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/target.py", line 67, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.924+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.923633Z[0m [[32m[1minfo     [0m] [1m    and self.config.get("dialect+driver") is not None[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:04.924+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:04.924070Z[0m [[32m[1minfo     [0m] [1mAssertionError: Need either the sqlalchemy_url to be set or host, port, user, password, and dialect+driver to be set[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:05.033+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:05.032997Z[0m [[31m[1merror    [0m] [1mExtraction failed             [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m"Config validation error: '/opt/meltano/config/tap-csv-latest.json' is not of type 'array', 'null' in config['files']"[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m
[2025-06-25T20:13:05.034+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:05.033280Z[0m [[31m[1merror    [0m] [1mLoading failed                [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m'AssertionError: Need either the sqlalchemy_url to be set or host, port, user, password, and dialect+driver to be set'[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m
[2025-06-25T20:13:05.034+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:05.033803Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Extractor and loader failed.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:05.034+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:05.034044Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:05.034+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:05.034247Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-06-25T201303--tap-csv-latest--target-postgres/79e2b211-927a-477e-a3d2-c556473ad464/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:05.035+0000] {docker.py:429} INFO - [2m2025-06-25T20:13:05.034472Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m79e2b211-927a-477e-a3d2-c556473ad464[0m [36mstate_id[0m=[35m2025-06-25T201303--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-25T20:13:05.047+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

ELT could not be completed: Extractor and loader failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-06-25T201303--tap-csv-latest--target-postgres/79e2b211-927a-477e-a3d2-c556473ad464/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2025-06-25T20:13:06.286+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-06-25T20:13:06.292+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250625T201205, start_date=20250625T201250, end_date=20250625T201306
[2025-06-25T20:13:06.315+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 133 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 186)
[2025-06-25T20:13:06.343+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-25T20:13:06.359+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
